"""Gyro Fix: un-invert gyro yaw for the ROG Xbox Ally X in Steam Input.

Steam Input flips the yaw sign for the USB product id InputPlumber's
`deck-uhid` target emulates for the Ally ("ASUS ROG Xbox Ally"). The simplest
working override is the InputPlumber device config with the y row of the IMU
mount matrix negated. InputPlumber loads /etc/inputplumber/devices.d before
/usr/share/inputplumber/devices, so a same-named file there wins.

The override is *generated* from the installed stock file (one line patched)
and stamped with the stock file's hash, so an InputPlumber update is detected
as "stale" and the override is regenerated instead of silently shadowing a
newer stock config with an old copy.

Caveats: only with the `deck-uhid` target; yaw through `ds5` targets becomes
inverted; when InputPlumber normalizes IMU data upstream this fix should be
turned off.
"""

from __future__ import annotations

import asyncio
import hashlib
import os
import re
import shutil
import time
import subprocess
from typing import Any

import decky

from ..base import Fix
from ..device import SUPPORTED_BOARDS
from ..sysfs import clean_env, dmi_board

STOCK = "/usr/share/inputplumber/devices/50-rog_xbox_ally.yaml"
OVERRIDE_DIR = "/etc/inputplumber/devices.d"
OVERRIDE = os.path.join(OVERRIDE_DIR, "50-rog_xbox_ally.yaml")
MARKER = "managed-by: ally-fix"
TARGETS_CACHE_S = 10.0

_MATRIX_Y = re.compile(r"^(\s*)y:\s*\[\s*0\s*,\s*-1\s*,\s*0\s*\]\s*$", re.M)
_HASH_LINE = re.compile(r"^# stock-sha256:\s*([0-9a-f]{64})\s*$", re.M)

DBUS_DEST = "org.shadowblip.InputPlumber"
COMPOSITE_IFACE = "org.shadowblip.Input.CompositeDevice"
_COMPOSITE_RE = re.compile(r"^/org/shadowblip/InputPlumber/CompositeDevice\d+$", re.M)


def _sha256(path: str) -> str:
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def _render(stock_text: str, stock_hash: str) -> str:
    patched, n = _MATRIX_Y.subn(r"\1y: [0, 1, 0]", stock_text, count=1)
    if n != 1:
        raise RuntimeError("stock config has no 'y: [0, -1, 0]' mount matrix row; upstream changed, fix may be obsolete")
    header = (
        f"# {MARKER}\n"
        f"# stock-sha256: {stock_hash}\n"
        "# Generated by the Ally Fix Decky plugin from the stock InputPlumber config.\n"
        "# Only change: the IMU mount matrix y row is negated to un-invert gyro yaw in\n"
        "# Steam Input via the deck-uhid target. Delete this file to return to stock.\n\n"
    )
    return header + patched


def _run_sync(argv: tuple[str, ...], timeout: float) -> tuple[int, str]:
    env = clean_env()
    exe = shutil.which(argv[0], path=env["PATH"]) or argv[0]
    try:
        proc = subprocess.run([exe, *argv[1:]], stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                              env=env, timeout=timeout, check=False)
    except subprocess.TimeoutExpired:
        return 124, "timeout"
    except OSError as exc:
        return 127, f"{argv[0]}: {exc}"
    return proc.returncode, proc.stdout.decode(errors="replace").strip()


async def _run(*argv: str, timeout: float = 20.0) -> tuple[int, str]:
    # Plain subprocess in a worker thread: asyncio subprocess support depends on
    # the host loop/thread setup, which the Decky runtime does not guarantee.
    return await asyncio.get_running_loop().run_in_executor(None, _run_sync, argv, timeout)


class GyroFix(Fix):
    id = "gyro"
    title = "Gyro Fix"

    # --- state inspection -----------------------------------------------
    @staticmethod
    def _override_text() -> str | None:
        try:
            with open(OVERRIDE, "r", encoding="utf-8") as f:
                return f.read()
        except OSError:
            return None

    def _override_state(self) -> str:
        """'absent' | 'foreign' | 'stale' | 'current'"""
        text = self._override_text()
        if text is None:
            return "absent"
        if MARKER not in text:
            return "foreign"
        m = _HASH_LINE.search(text)
        if not m or not os.path.exists(STOCK) or m.group(1) != _sha256(STOCK):
            return "stale"
        return "current"

    async def _composite_path(self) -> str | None:
        """Find the composite device that is the Ally itself (by its Name)."""
        code, out = await _run("busctl", "--system", "tree", "--list", DBUS_DEST, timeout=5)
        if code != 0:
            return None
        paths = _COMPOSITE_RE.findall(out)
        for path in paths:
            c, o = await _run("busctl", "--system", "get-property", DBUS_DEST, path, COMPOSITE_IFACE, "Name", timeout=5)
            if c == 0 and "ally" in o.lower():
                return path
        return paths[0] if paths else None

    async def _target_types(self) -> list[str]:
        composite = await self._composite_path()
        if composite is None:
            return []
        code, out = await _run("busctl", "--system", "get-property", DBUS_DEST, composite,
                               COMPOSITE_IFACE, "TargetDevices", timeout=5)
        if code != 0:
            # Transient while InputPlumber restarts (object not yet exported) — not worth a warning.
            decky.logger.debug("[gyro] busctl TargetDevices failed (%d): %s", code, out[:300])
            return []
        types: list[str] = []
        decky.logger.debug("[gyro] TargetDevices raw: %r", out[:300])
        for path in re.findall(r'"([^"]+)"', out):
            c, o = await _run("busctl", "--system", "get-property", DBUS_DEST, path,
                              "org.shadowblip.Input.Target", "DeviceType", timeout=5)
            decky.logger.debug("[gyro] DeviceType %s -> %d %r", path, c, o[:200])
            if c == 0:
                t = re.findall(r'"([^"]+)"', o)
                if t:
                    types.append(t[0])
        return types

    # --- Fix interface ---------------------------------------------------
    def supported(self) -> tuple[bool, str]:
        board = dmi_board()
        if board not in SUPPORTED_BOARDS:
            return False, f"verified only on ROG Xbox Ally X (board {board or 'unknown'})"
        if not os.path.exists(STOCK):
            return False, "InputPlumber config for ROG Xbox Ally not found"
        if shutil.which("systemctl") is None:
            return False, "systemctl not available"
        return True, ""

    def is_applied(self) -> bool:
        return self._override_state() == "current"

    def status(self):  # type: ignore[override]
        st = super().status()
        if st.state in ("applied", "not_applied"):
            ov = self._override_state()
            if ov == "stale":
                st.state = "stale"
                st.message = "InputPlumber was updated; the override needs to be regenerated"
            elif ov == "foreign":
                st.state = "error"
                st.message = f"{OVERRIDE} exists but was not created by Ally Fix"
        return st

    async def apply(self) -> None:
        state = self._override_state()
        if state == "foreign":
            raise RuntimeError(f"{OVERRIDE} exists and is not managed by Ally Fix; remove it manually first")
        stock_hash = _sha256(STOCK)
        with open(STOCK, "r", encoding="utf-8") as f:
            stock_text = f.read()
        try:
            text = _render(stock_text, stock_hash)
        except RuntimeError:
            if state == "stale":
                # Never leave an outdated full copy shadowing a newer stock config.
                os.remove(OVERRIDE)
                decky.logger.warning("[gyro] stock config changed and cannot be patched; stale override removed")
                await self._restart_inputplumber()
            raise
        if self._override_text() == text:
            decky.logger.info("[gyro] override already current")
            return
        os.makedirs(OVERRIDE_DIR, mode=0o755, exist_ok=True)
        tmp = OVERRIDE + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        os.chmod(tmp, 0o644)
        os.replace(tmp, OVERRIDE)
        decky.logger.info("[gyro] override written to %s", OVERRIDE)
        await self._restart_inputplumber()

    async def revert(self) -> None:
        state = self._override_state()
        if state == "absent":
            return
        if state == "foreign":
            raise RuntimeError(f"{OVERRIDE} is not managed by Ally Fix; not removing it")
        os.remove(OVERRIDE)
        decky.logger.info("[gyro] override removed")
        await self._restart_inputplumber()

    async def _restart_inputplumber(self) -> None:
        code, out = await _run("systemctl", "restart", "inputplumber")
        if code != 0:
            raise RuntimeError(f"systemctl restart inputplumber failed ({code}): {out}")
        decky.logger.info("[gyro] inputplumber restarted")

    def details(self) -> dict[str, Any]:
        return {
            "board": dmi_board(),
            "override": self._override_state(),
            "override_path": OVERRIDE,
        }

    _targets_cache: tuple[float, list[str]] = (0.0, [])

    async def details_async(self) -> dict[str, Any]:
        d = self.details()
        now = time.monotonic()
        ts, cached = self._targets_cache
        if now - ts < TARGETS_CACHE_S:
            targets = cached
        else:
            targets = await self._target_types()
            self._targets_cache = (now, targets)
        d["targets"] = targets
        d["deck_uhid"] = "deck-uhid" in targets
        return d

    async def start_background(self) -> None:
        # InputPlumber update while we were enabled: regenerate.
        if self.enabled and self.supported()[0] and self._override_state() == "stale":
            decky.logger.info("[gyro] stock config changed since override was generated; regenerating")
            await self.reapply_if_enabled()
